services:
  db:
    image: mariadb:10.9.2
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=kenka
      - MYSQL_DATABASE=kenka
      - MYSQL_USER=kenka
      - MYSQL_PASSWORD=kenka
    ports:
      - 33061:3306
    networks:
      wordpress:
        aliases:
          - db.kenka.dev
  web:
    image: vhphan/kenka:2.0
    ports:
      - 80:80
    volumes:
      - './:/var/www/html'
      - './docker/php/conf.d/php.ini:/usr/local/etc/php/php.ini'
    links:
      - db
    networks:
      wordpress:
        aliases:
          - web.kenka.dev
volumes:
  db_data: {}
networks:
  wordpress:
    driver: bridge